import { useState, useEffect, useCallback } from 'react';

/**
 * Shape of public/data/stats.json (generated by scripts/generate-data.ts).
 * Every field is derived from real scan data or accumulated history snapshots.
 */
export interface EcosystemOverview {
  totalPlugins: number;
  totalMarketplaces: number;
  totalDevelopers: number;
  totalStars: number;
  lastUpdated: string;
  growthRate: {
    plugins: number | null;
    marketplaces: number | null;
    developers: number | null;
    stars: number | null;
  };
}

export interface TrendPoint {
  date: string;
  value: number | null;
  change?: number;
}

export interface CategoryCount {
  id: string;
  name: string;
  count: number;
  description: string;
}

export interface EcosystemQuality {
  manifestCoverage: { withManifest: number; total: number; rate: number };
  maintenance: {
    recentlyUpdated: number;
    recentlyUpdatedRate: number;
    staleOver180Days: number;
    /** Days until half the catalog has been touched — robust against growth skew. */
    medianDaysSinceUpdate?: number | null;
  };
  /** Share of plugins shipping at least one skill. Added after the initial
   * daily snapshots — absent in stats.json until the pipeline regenerates. */
  pluginSkills?: { withSkills: number; total: number; rate: number };
  avgStarsPerMarketplace: number;
  /** Share of marketplaces with at least `threshold` stars (see generate-data.ts). */
  traction: { count: number; total: number; share: number; threshold: number };
}

export interface EcosystemStatsData extends EcosystemQuality {
  overview: EcosystemOverview;
  plugins: TrendPoint[];
  marketplaces: TrendPoint[];
  developers: TrendPoint[];
  stars: TrendPoint[];
  starred: TrendPoint[];
  period: string;
  aggregation: string;
  categories: CategoryCount[];
  insights: string[];
}

interface EcosystemStatsResponse {
  success: boolean;
  data: EcosystemStatsData;
  meta: { timestamp: string; requestId: string; responseTime: number };
}

export interface UseEcosystemStatsReturn {
  data: EcosystemStatsData | null;
  metaTimestamp: string | null;
  loading: boolean;
  error: string | null;
  refresh: () => void;
}

// Module-level cache: the homepage previously fetched stats.json four times
// (once per dashboard section); every consumer now shares one request.
let cache: Promise<EcosystemStatsResponse> | null = null;
const listeners = new Set<() => void>();

function fetchStats(): Promise<EcosystemStatsResponse> {
  if (!cache) {
    cache = fetch(`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/data/stats.json`).then((r) => {
      if (!r.ok) throw new Error(`stats.json ${r.status}`);
      return r.json();
    });
  }
  return cache;
}

/**
 * Shared, cached loader for the generated ecosystem stats.
 * `refresh()` invalidates the cache and refetches for all consumers.
 */
export function useEcosystemStats(): UseEcosystemStatsReturn {
  const [response, setResponse] = useState<EcosystemStatsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [version, setVersion] = useState(0);

  const refresh = useCallback(() => {
    cache = null;
    setVersion((v) => v + 1);
    listeners.forEach((l) => l);
  }, []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    fetchStats()
      .then((res) => {
        if (!cancelled) setResponse(res);
      })
      .catch((err) => {
        if (!cancelled) {
          console.error('Error loading ecosystem stats:', err);
          setError('Failed to load ecosystem stats');
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [version]);

  // Keep every mounted consumer in sync after a refresh invalidates the cache.
  useEffect(() => {
    const listener = () => setVersion((v) => v + 1);
    listeners.add(listener);
    return () => {
      listeners.delete(listener);
    };
  }, []);

  return {
    data: response?.data ?? null,
    metaTimestamp: response?.meta?.timestamp ?? null,
    loading,
    error,
    refresh,
  };
}
