import { useState, useEffect } from 'react';
import { toCatalogPlugin, CatalogPlugin } from './usePluginData';

interface UsePluginShardReturn {
  plugins: CatalogPlugin[];
  loading: boolean;
  error: string | null;
}

/**
 * Loads one marketplace's full plugin records from its shard
 * (public/data/plugins/<marketplaceId>.json), generated by the pipeline.
 * Use usePluginData for the compact cross-marketplace index.
 */
export function usePluginShard(marketplaceId: string | undefined): UsePluginShardReturn {
  const [plugins, setPlugins] = useState<CatalogPlugin[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // No marketplace to resolve (yet) — report settled-empty, not an error.
    if (!marketplaceId) {
      setPlugins([]);
      setLoading(false);
      setError(null);
      return;
    }

    let cancelled = false;
    async function fetchShard() {
      try {
        setLoading(true);
        setError(null);
        // Base path is required on GitHub Pages (site served under /<repo>/);
        // a relative path resolves against the current page URL and 404s.
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/data/plugins/${encodeURIComponent(
            marketplaceId!
          )}.json`
        );
        if (!response.ok) {
          throw new Error(`plugins/${marketplaceId}.json ${response.status}`);
        }
        const json = await response.json();
        if (cancelled) return;
        const entries = Array.isArray(json) ? json : [];
        setPlugins(entries.map(toCatalogPlugin));
      } catch (err) {
        if (!cancelled) {
          console.error('Error loading plugin shard:', err);
          setError('Failed to load plugin data');
          setPlugins([]);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    fetchShard();
    return () => {
      cancelled = true;
    };
  }, [marketplaceId]);

  return {
    plugins: plugins || [],
    loading,
    error,
  };
}
